InheritVideoUploadWebApp/Models/FileUploadModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace InheritVideoUploadWebApp.Models
{
    public class FileUploadModel
    {
        [DataType(DataType.Upload)]
        [Display(Name = "Upload Video")]
        [Required(ErrorMessage = "Please choose Video to upload.")]
        public string file { get; set; }
    }
}

InheritVideoUploadWebApp/Controllers/FileUploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;
using System.Threading.Tasks;
using System.Net.Http;
using System.Collections.Specialized;

namespace InheritVideoUploadWebApp.Controllers
{
    public class FileUploadController : Controller
    {
        // GET: FileUpload
        public ActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public async Task<ActionResult> UploadFiles(HttpPostedFileBase file)
        {
            Boolean fileOK = false;
            if (ModelState.IsValid)
            {
                try
                {
                    if (file != null)
                    {
                        String fileExtension =System.IO.Path.GetExtension(file.FileName).ToLower();
                        String[] allowedExtensions ={".mp4", ".flv"};
                        for (int i = 0; i < allowedExtensions.Length; i++)
                        {
                            if (fileExtension == allowedExtensions[i])
                            {
                                fileOK = true;
                            }
                        }
                        if (fileOK)
                        {
                            string path = Path.Combine(Server.MapPath("~/UploadedFiles"), Path.GetFileName(file.FileName));
                            file.SaveAs(path);
                            MemoryStream st = new MemoryStream();
                            var stream = file.InputStream;
                            stream.CopyTo(st);
                            var bytearray = st.ToArray();
                            UploadMultipart(bytearray, file.FileName, file.ContentType, "http://localhost:12214/api/Files/Upload");
                        }
                        else
                        {
                            ViewBag.FileStatus = "Invalid file format.";
                            return View("Index");
                        }
                    }
                    ViewBag.FileStatus = "File uploaded successfully.";
                }
                catch (Exception ex)
                {

                    ViewBag.FileStatus = "Error while file uploading.";
                }

            }
            return View("Index");
        }
        public void UploadMultipart(byte[] file, string filename, string contentType, string url)
        {
            var webClient = new WebClient();
            string boundary = "------------------------" + DateTime.Now.Ticks.ToString("x");
            webClient.Headers.Add("Content-Type", "multipart/form-data; boundary=" + boundary);
            var fileData = webClient.Encoding.GetString(file);
            var package = string.Format("--{0}\r\nContent-Disposition: form-data; name=\"file\"; filename=\"{1}\"\r\nContent-Type: {2}\r\n\r\n{3}\r\n--{0}--\r\n", boundary, filename, contentType, fileData);

            var nfile = webClient.Encoding.GetBytes(package);
            //webClient.UploadProgressChanged
            
           var res = webClient.UploadData(new Uri(url), nfile);
        }
        private static string sendHttpRequest(string url, NameValueCollection values, NameValueCollection files = null)
        {
            string boundary = "----------------------------" + DateTime.Now.Ticks.ToString("x");
            // The first boundary
            byte[] boundaryBytes = System.Text.Encoding.UTF8.GetBytes("\r\n--" + boundary + "\r\n");
            // The last boundary
            byte[] trailer = System.Text.Encoding.UTF8.GetBytes("\r\n--" + boundary + "--\r\n");
            // The first time it itereates, we need to make sure it doesn't put too many new paragraphs down or it completely messes up poor webbrick
            byte[] boundaryBytesF = System.Text.Encoding.ASCII.GetBytes("--" + boundary + "\r\n");

            // Create the request and set parameters
            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(url);
            request.ContentType = "multipart/form-data; boundary=" + boundary;
            request.Method = "POST";
            request.KeepAlive = true;
            request.Credentials = System.Net.CredentialCache.DefaultCredentials;

            // Get request stream
            Stream requestStream = request.GetRequestStream();

            foreach (string key in values.Keys)
            {
                // Write item to stream
                byte[] formItemBytes = System.Text.Encoding.UTF8.GetBytes(string.Format("Content-Disposition: form-data; name=\"{0}\";\r\n\r\n{1}", key, values[key]));
                requestStream.Write(boundaryBytes, 0, boundaryBytes.Length);
                requestStream.Write(formItemBytes, 0, formItemBytes.Length);
            }

            if (files != null)
            {
                foreach (string key in files.Keys)
                {
                    if (System.IO.File.Exists(files[key]))
                    {
                        int bytesRead = 0;
                        byte[] buffer = new byte[2048];
                        byte[] formItemBytes = System.Text.Encoding.UTF8.GetBytes(string.Format("Content-Disposition: form-data; name=\"{0}\"; filename=\"{1}\"\r\nContent-Type: application/octet-stream\r\n\r\n", key, files[key]));
                        requestStream.Write(boundaryBytes, 0, boundaryBytes.Length);
                        requestStream.Write(formItemBytes, 0, formItemBytes.Length);

                        using (FileStream fileStream = new FileStream(files[key], FileMode.Open, FileAccess.Read))
                        {
                            while ((bytesRead = fileStream.Read(buffer, 0, buffer.Length)) != 0)
                            {
                                // Write file content to stream, byte by byte
                                requestStream.Write(buffer, 0, bytesRead);
                            }

                            fileStream.Close();
                        }
                    }
                }
            }

            // Write trailer and close stream
            requestStream.Write(trailer, 0, trailer.Length);
            requestStream.Close();

            using (StreamReader reader = new StreamReader(request.GetResponse().GetResponseStream()))
            {
                return reader.ReadToEnd();
            };
        }
        //[HttpPost]
        //public ActionResult UploadFiles(HttpPostedFileBase file)
        //{
        //    Boolean fileOK = false;
        //    if (ModelState.IsValid)
        //    {
        //        try
        //        {
        //            if (file != null)
        //            {
        //                String fileExtension = System.IO.Path.GetExtension(file.FileName).ToLower();

        //                String[] allowedExtensions = { ".mp4", ".flv" };
        //                for (int i = 0; i < allowedExtensions.Length; i++)
        //                {
        //                    if (fileExtension == allowedExtensions[i])
        //                    {
        //                        fileOK = true;
        //                    }
        //                }
        //                if (fileOK)
        //                {
        //                    string path = Path.Combine(Server.MapPath("~/UploadedFiles"), Path.GetFileName(file.FileName));
        //                    file.SaveAs(path);
        //                }
        //                else
        //                {
        //                    ViewBag.FileStatus = "Invalid file format.";
        //                    return View("Index");
        //                }
        //            }
        //            ViewBag.FileStatus = "File uploaded successfully.";
        //        }
        //        catch (Exception)
        //        {

        //            ViewBag.FileStatus = "Error while file uploading.";
        //        }

        //    }
        //    return View("Index");
        //}


    }
}

InheritVideoUploadWebApp/Views/FileUpload/Index.cshtml
@model InheritVideoUploadWebApp.Models.FileUploadModel

@{
    ViewBag.Title = "Index";
}

@using (Html.BeginForm("UploadFiles", "FileUpload", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.file, htmlAttributes: new { @class = "control-label col-md-2" })
        @*<div class="col-md-10">
                @Html.EditorFor(model => model.file, new { htmlAttributes = new { @class = "form-control", @type = "file" } })
                @Html.ValidationMessageFor(model => model.file, "", new { @class = "text-danger" })
            </div>*@
    </div>
    <input type="file" name="file" id="sel-file" />
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input id="upload-files" value="Upload" class="btn btn-primary" />
        </div>
    </div>

    <center>
        <div id="val"></div>
    </center>
    <div id="myProgress">

        <div id="myBar"></div>
    </div>
    <div class="form-group">
        <div class="col-md-offset-2 col-md-10 text-success">
            @ViewBag.FileStatus
        </div>
    </div>
</div>
}
<style>
    #myProgress {
        width: 100%;
        background-color: grey;
    }

    #myBar {
        width: 1%;
        height: 30px;
        background-color: green;
    }
</style>
<script type="text/javascript">
    jQuery(document).ready(function () {
        var elem = document.getElementById("myBar");  
        $('#upload-files').on('click', function () {
            var file = $('#sel-file').get(0).files[0],
                formData = new FormData();
            file.name = guid() + "." + "mp4";
            formData.append('file', file);
            console.log(file);
            $.ajax({
                url: 'http://localhost:12214/api/Files/Upload',
                type: 'POST',
                contentType: false,
                cache: false,
                processData: false,
                data: formData,
                xhr: function () {
                    var jqXHR = null;
                    if (window.ActiveXObject) {
                        jqXHR = new window.ActiveXObject("Microsoft.XMLHTTP");
                    }
                    else {
                        jqXHR = new window.XMLHttpRequest();
                    }
                    //Upload progress
                    jqXHR.upload.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = Math.round((evt.loaded * 100) / evt.total);
                            //Do something with upload progress
                            $('#val').html(percentComplete + '%');
                            elem.style.width = percentComplete + '%'; 
                            console.log('Uploaded percent', percentComplete);
                        }
                    }, false);
                    //Download progress
                    jqXHR.addEventListener("progress", function (evt) {
                        if (evt.lengthComputable) {
                            var percentComplete = Math.round((evt.loaded * 100) / evt.total);
                            //Do something with download progress
                            $('#val').html(percentComplete + '%');
                            elem.style.width = percentComplete + '%'; 
                            console.log('Downloaded percent', percentComplete);
                        }
                    }, false);
                    return jqXHR;
                },
                success: function (data) {
                    //Do something success-ish
                    console.log('Completed.');
                }
            });
        });
    });
    function guid() {
        function s4() {
            return Math.floor((1 + Math.random()) * 0x10000)
                .toString(16)
                .substring(1);
        }
        return s4() + s4() + '-' + s4() + '-' + s4() + '-' + s4() + '-' + s4() + s4() + s4();
    }
</script>

InheritVideoUploadWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>